import { HomeIcon, InboxIcon, InformationCircleIcon, PhoneIcon, TicketIcon } from "@heroicons/react/24/outline"
import Link from "next/link"
import { useState, useEffect } from "react"
import { useRouter } from 'next/router'
import { LuCopyright } from "react-icons/lu";
import { GrFacebook } from "react-icons/gr";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


interface Props {
  children: React.ReactNode
}


// path config
const paths = [
  {
    path: '/login',
    label: 'หน้าหลัก',
    icon: <HomeIcon className="w-9 h-9" />
    // img: /1.png
  },
  {
    path: '/booking',
    label: 'ตั๋วของฉัน',
    icon: <TicketIcon className="w-9 h-9" />
    // img: /2.png ตีมือ
  },
  {
    path: '/contact-us',
    label: 'ติดต่อเรา',
    icon: <PhoneIcon className="w-9 h-9" />
  },
  {
    path: '/help-center',
    label: 'ช่วยเหลือ',
    icon: <InformationCircleIcon className="w-9 h-9" />
  }
]

const Layout: React.FC<Props> = ({ children }) => {
  const [open, toggle] = useState<boolean>(false)

  const router = useRouter()
  const isLoginPage = router.pathname === '/';
  const isRegisterPage = router.pathname === '/register';
  const isForgotpasswordPage = router.pathname === '/forgotpassword';
  const isResetpasswordPage = router.pathname === '/resetpassword';
  const isAdminPage = router.pathname === '/adminpage'

  const handleLogout = async () => {
    localStorage.removeItem('token')
    window.location.href = "/";
  }
  

  useEffect(() => {
    // close sidebar every time when pathname changed
    toggle(false)
  }, [router.pathname]) // http://localhost:3000/contact-us => /contact-us

  if (isLoginPage || isRegisterPage || isForgotpasswordPage || isResetpasswordPage || isAdminPage) {
    // Render layout without navbar and footer for login and register pages
    return <main className="bg-white min-h-screen">{children}</main>;
  }





  
  return (
    <main className={`bg-white min-h-screen`}>
      {
        // navbar
        <nav className="sticky z-10 inset-0 py-2 px-6 bg-white flex justify-between shadow-lg items-center ">
          <div className="flex">
            <Link href='/login'>
              <img src="/logo.png" alt="logo" className="h-10" />
            </Link>
          </div>
          <div className="flex gap-8 text-lg items-center justify-start">
            {
              // list of buttons
              paths.map(({
                path, label,
                // , img
              }, idx) => (
                <Link href={path} key={idx}>
                  <div className={`flex items-center justify-evenly ${router.pathname === path ? 'text-blue-800' : 'text-black'}`}>
                    <p className="text-xl hover:text-blue-900">{label}</p>
                  </div>
                </Link>
              ))
            }
            {/*<button className=" hover:text-blue-800 text-xl py-1.5 px-3 ">
              <Link href='/login'>Login</Link>
            </button>
            <button className="bg-blue-500 hover:bg-blue-700 text-white text-xl py-1.5 px-3 rounded-full">
              <Link href='/register'>Register</Link>
          </button>*/}
            <button
              type="button"
              onClick={handleLogout}
              className="bg-blue-800 hover:bg-blue-600 text-white text-xl py-1.5 px-3 rounded-full "
            >ออกจากระบบ
            </button>
          </div>
        </nav>
      }
      <div className="flex flex-col mb-12">
        {/*<img src="/1.png" alt="banner" className="object-cover w-full h-72"/>*}
        {/* <img src={img} alt="banner" className="object-cover w-full" /> */}
        <div className="items-center w-full">
          {children}
        </div>
      </div>

      {/*<footer className="fixed bottom-0 inset-x-0 bg-blue-800 shadow-lg text-center text-white">
        {



        }
       
        <span> <LuCopyright className="h-4 w-4" />2023 - All Rights Reserved</span>
      </footer>*/

        <footer className="flex flex-col justify-center items-center gap-6 p-10 bg-blue-800 text-white text-center bottom-0 w-full">
          <div className="flex flex-row gap-4">
            <div className="flex gap-8 text-lg items-center">
              {
                // list of buttons
                paths.map(({
                  path, label,
                  // , img
                }, idx) => (
                  <Link href={path} key={idx}>
                    <div className="flex items-center justify-evenly">
                      <p className="text-xl white  hover:text-blue-400 ">{label}</p>
                    </div>
                  </Link>
                ))
              }
            </div>
          </div>
          <div>
            <div className="flex justify-center gap-4">
              <a>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current">
                  <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
                </svg>
              </a>
              <a>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current">
                  <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
                </svg>
              </a>
              <a>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current">
                  <path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
                </svg>
              </a>
            </div>
          </div>
          <aside>
            <p>Copyright © 2023 - All right reserved by BTS</p>
          </aside>
        </footer>
      }

    </main >
  )
}

export default Layout
